language: python

python:
- 3.6
- 3.7

before_install:
- pip install poetry

install:
- poetry install -E yaml -E toml

script:
- poetry run pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
