[tool.poetry]
name = "python-configuration"
version = "0.1.0"
description = "A library to load configuration parameters from multiple sources and formats"
authors = [
    "Tiago Requeijo <tiago.requeijo.dev@gmail.com>"
]
readme = 'README.md'
license = "MIT"
repository = "https://github.com/tr11/python-configuration"
homepage = "https://github.com/tr11/python-configuration"
keywords = ['configuration', 'settings', 'json', 'yaml', 'toml', 'ini']
packages = [
    { include = "config" },
]

[tool.poetry.dependencies]
python = "^3.5"
pyyaml = {version = "^5.1", optional = true}
toml = {version = "^0.10.0",optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-cov = "^2.6"
pytest-flake8 = "^1.0"
mypy = "^0.711.0"
pytest-mypy = "^0.3.2"

[tool.poetry.extras]
yaml = ["pyyaml"]
toml = ["toml"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
